# Generated by Django 5.1.4 on 2024-12-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overspeedincident',
            name='number_plate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overspeedincident',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
