# Generated by Django 5.1.4 on 2024-12-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_overspeedincident_number_plate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(choices=[('Location 1', 'Location 1'), ('Location 2', 'Location 2'), ('Location 3', 'Location 3'), ('Location 4', 'Location 4'), ('Location 5', 'Location 5'), ('Location 6', 'Location 6'), ('Location 7', 'Location 7'), ('Location 8', 'Location 8'), ('Location 9', 'Location 9'), ('Location 10', 'Location 10')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='incident_photos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
