# Generated by Django 5.1.4 on 2025-01-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_locationcontrolroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationControlRoom',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
